import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: "500",
});
const myFont = localFont({
  src: "../../public/fonts/advanced-popups-icons.woff",
});

export const metadata: Metadata = {
  title: "Pixel render",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${myFont.className} ${poppins.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
